# NumPy Exercises

1. Import numpy as np and see the version

2. How to create a 1D array?

3. How to extract items that satisfy a given condition from 1D array?

4. How to replace items that satisfy a condition with another value in numpy array?

5. How to reshape an array?

6. How to stack two arrays vertically?

7. How to stack two arrays horizontally?

8. How to get the positions where elements of two arrays match?

9. How to reverse the columns of a 2D array?

10. How to compute the euclidean distance between two arrays?

In [1]:
import numpy as np
print(np.__version__)

1.21.1


In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr_odd = arr[arr % 2 == 1]
arr_odd

array([1, 3, 5, 7, 9])

In [4]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
arr = np.arange(10)
print(arr)
arr.reshape(10, -1)  # Setting to -1 automatically decides the number of columns

[0 1 2 3 4 5 6 7 8 9]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
a = np.arange(10).reshape(2,-1)
print('a \n', a)
b = np.repeat(1, 10).reshape(2,-1)
print('b \n', b)

# Answers
# Method 1:
x = np.concatenate([a, b], axis=0)
print('x \n', x)

# Method 2:
y = np.vstack([a, b])
print('y \n', y)

# Method 3:
z = np.r_[a, b]
print('z \n', z)

a 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
x 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
y 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
z 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
a = np.arange(10).reshape(2,-1)
print('a \n', a)
b = np.repeat(1, 10).reshape(2,-1)
print('b \n', b)

# Answers
# Method 1:
x = np.concatenate([a, b], axis=1)
print('x \n', x)

# Method 2:
y = np.hstack([a, b])
print('y \n', y)

# Method 3:
z = np.c_[a, b]
print('z \n', z)

a 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
x 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
y 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
z 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [20]:
c = a+b
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

same = np.where(a == b)
same

(array([1, 3, 5, 7]),)

In [9]:
# Input
arr = np.arange(9).reshape(3,3)
print(arr)

# Solution
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [22]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)
print(a.argsort().argsort())

Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]


The Euclidean distance formula is used to find the distance between two points on a plane. This formula says the distance between two points (x1, y1) and (x2, y2) is d = √[(x2 – x1)^2 + (y2 – y1)^2].

In [11]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
# Solution
dist = np.linalg.norm(a-b)
dist

6.708203932499369